#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdmObjId.h 
 * \brief Automatically generated header file mdmObjId.h
 */




#endif /* __MDM_OBJECTID_H__ */
